### ISSUE TITLE
composer install issue with version 3.7

### ISSUE THREAD

**Issue by ibastevan** [QoboLtd/cakephp-utils#182]
When i try to install this using composer require qobo/cakephp-utils
I get error -

 Problem 1
    - qobo/cakephp-utils v12.2.1 requires cakephp/cakephp ^3.5 <3.7 -> satisfiable by cakephp/cakephp[3.5.0, 3.5.0-RC1, 3.5.0-RC2, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.2, 3.5.3, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9, 3.6.0, 3.6.0-RC1, 3.6.0-RC2, 3.6.0-beta1, 3.6.0-beta2, 3.6.0-beta3, 3.6.1, 3.6.10, 3.6.11, 3.6.12, 3.6.13, 3.6.14, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.6.7, 3.6.8, 3.6.9] but these conflict with your requirements or minimum-stability.

I am running cakephp 3.7, trying to install qobo/survey

I also tried in composer.json -
"minimum-stability": "dev"

Update -
Ok so i managed to get it up and running on Cake 3.6.
I added to composer.json "require": { "burzum/cakephp-file-storage": "dev-branch-2.0" }
    "repositories": [{
            "type": "git",
            "url": "https://github.com/QoboLtd/cakephp-file-storage.git"
    }],
and 
"minimum-stability": "dev"

Then ran composer update in CLI

**Comment by anvyst** [comment]
Hey @ibastevan, 

Sorry for the reply that took so long.
The plugin is currently tightly bond to CakePHP 3.6.x version.
We'll be removing this version lock in close future, but for now unfortunately you can run this plugin only for v3.6.x
